# Generated by Django 3.1.4 on 2021-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210105_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img_lights.jpg', upload_to='post_pics/'),
        ),
    ]
