# Generated by Django 3.1.4 on 2021-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img_lights.jpg', upload_to='post_pics'),
        ),
    ]
